### ISSUE TITLE
Bug with "load_byfly_data" task

### ISSUE THREAD

**Issue by Shpilevskiy** [MrLokans/isp_availability_service#12]
The following error appears when Celery try to perform а byfly task

![_022](https://cloud.githubusercontent.com/assets/11997804/16775068/9a3919a8-4867-11e6-8989-9d94b521ed3a.png)

**Comment by Shpilevskiy** [comment]
this error appears occasionally, so, try to start this task a few times

**Comment by MrLokans** [comment]
Related topic: https://github.com/gevent/gevent/issues/585
