### ISSUE TITLE
[UI] Blinking dropdown lists

### ISSUE THREAD

**Issue by Shpilevskiy** [MrLokans/isp_availability_service#31]
When user tries to type something in city or street field, typeahead dropdown list starts blinking, but its animation should be smoother, like in those examples: https://twitter.github.io/typeahead.js/examples/

**Comment by MrLokans** [comment]
There are no obvious solutions for this problem, see also the following discussion: [link](https://github.com/twitter/typeahead.js/issues/176)

**Comment by Shpilevskiy** [comment]
Ok, we selected Jquery-Autocmplete instead of Typeahead and i closed this at https://github.com/MrLokans/isp_availability_service/commit/836e2bcb4266c09c45e3a115d18fadff4fea8496
