### ISSUE TITLE
[Utils] Imports are not working as expected

### ISSUE THREAD

**Issue by Shpilevskiy** [MrLokans/isp_availability_service#32]
For example, we have import of exception, it works well for container, but when we try to execute  it locally, its not working. To repeat this, you can try to start 'fill_db.py', it trying to import 'call_db_filling' from 'parser_routines.utils', which in turn imports 'exceptions', and at this moment it should fall.

**Comment by MrLokans** [comment]
I will solve this problem by appending parser_routines directory to python path. Yeah, it is not elegant at all, but it will fix existing issues quickly.
