### ISSUE TITLE
[Parser service] Creating db models while docker containers up

### ISSUE THREAD

**Issue by Shpilevskiy** [MrLokans/isp_availability_service#41]
After rebasing db models and utils into another module we have a problem with creating db models. For a while we can link 'bin' and 'parser_routins', but we need something better to close this issue.

**Comment by Shpilevskiy** [comment]
temporary solution 4011425992c2742e72b072931811a758b99df02d

**Comment by MrLokans** [comment]
For development and testing purposes your temporary solution is pretty nice, ok.
