### ISSUE TITLE
[API] Email verification

### ISSUE THREAD

**Issue by Shpilevskiy** [MrLokans/isp_availability_service#50]
We need email verification in subscribe endpoint. [This solution](https://github.com/syrusakbary/validate_email) is look pretty nice, lets discuss, what of those feature we need to use, or, maybe, someone has another ideas?

**Comment by MrLokans** [comment]
This solutions is appropriate, but I think it is better to avoid checking DNS MX records - simple check for e-mail address validity will be enough
